### ISSUE TITLE
Filter results by quality

### ISSUE THREAD

**Issue by leinad87** [alashow/music#19]
Could be a good idea to filter results by quality removing those which has not enough quality

**Comment by alashow** [comment]
Checking quality of each search result item would be very slow and VK will block my server's ip and/or my application/tokens.

Even if VK API won't block my requests,  as far as I know, calculating mp3's quality would require at least size of mp3, which is not fast process:
1. ~50 ms getting audio object (duration & mp3 link)
2. Getting size of mp3 from link with HEAD request (~100-150 ms)

Each audio would require about 200 ms for checking quality.
Even checking quality was faster, VK API allows only 1-2 requests per second (from same IP). Because sometimes it throws "Too much requests per second" error.

Anyways, normally, mp3's in VK are good,  at least with 128 kbits.
